USE h22_ebd_projet1;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS tblSessions;
CREATE TABLE tblSessions(
idSession INT PRIMARY KEY AUTO_INCREMENT,
noProgramme VARCHAR(6),
annee SMALLINT NOT NULL,
saison VARCHAR(7) NOT NULL
);

DROP TABLE IF EXISTS tblProgrammes;
CREATE TABLE tblProgrammes(
noProgramme VARCHAR(6) PRIMARY KEY,
nomProgramme VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS tblProgrammeCours;
CREATE TABLE tblProgrammeCours(
noProgramme VARCHAR(6),
noCours VARCHAR(15),
PRIMARY KEY(noProgramme, noCours)
);

DROP TABLE IF EXISTS tblCours;
CREATE TABLE tblCours(
noCours VARCHAR(15) PRIMARY KEY,
nomCours VARCHAR(50) NOT NULL,
description VARCHAR(255)
);

DROP TABLE IF EXISTS tblTaches;
CREATE TABLE tblTaches(
idTache INT PRIMARY KEY AUTO_INCREMENT,
noCours VARCHAR(15),
idStatut INT,
titre VARCHAR(32) NOT NULL,
dateDebut DATETIME,
dateFin DATETIME NOT NULL,
description VARCHAR(255)
);

DROP TABLE IF EXISTS tblStatut;
CREATE TABLE tblStatut(
idStatut INT PRIMARY KEY AUTO_INCREMENT,
etat VARCHAR(16) NOT NULL
);

DROP TABLE IF EXISTS tblRappels;
CREATE TABLE tblRappels(
idRappel INT PRIMARY KEY AUTO_INCREMENT,
idTache INT,
titre VARCHAR(32) NOT NULL,
message VARCHAR(255)
);

DROP TABLE IF EXISTS tblCategorieTaches;
CREATE TABLE tblCategorieTaches(
idCategorie INT,
idTache INT
);

DROP TABLE IF EXISTS tblCategories;
CREATE TABLE tblCategories(
idCategorie INT PRIMARY KEY AUTO_INCREMENT,
nom VARCHAR(16) NOT NULL
);
SET FOREIGN_KEY_CHECKS = 1;